\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{replab}[2022/12/20 v1.0]

% --- Configuración básica ---

\LoadClass[11pt, letterpaper, twoside, twocolumn]{article}

% Configuración de idioma
\RequirePackage[english, spanish, mexico, es-noitemize, es-noindentfirst, ]{babel}

% Matemáticas avanzadas
\RequirePackage[tbtags]{mathtools}% Funciones matemáticas avanzadas (carga amsmath internamente)
\RequirePackage{amssymb, amsthm, siunitx}% Funciones matemáticas adicionales y unidades del SI
\RequirePackage[nolimits]{cmupint}% Integrales rectas

% Configuración de fuente
\RequirePackage{lmodern}
\RequirePackage[T1]{fontenc}
\renewcommand{\ttdefault}{lmtt}% Fuente mono
\renewcommand{\rmdefault}{lmr}% Fuente serif
\renewcommand{\sfdefault}{lmss}% Fuente sans-serif

% Diseño del documento
\RequirePackage[left=1.5cm, right=1.5cm, top=0.75in, bottom=0.55in, headheight=23pt, headsep=\baselineskip, twocolumn]{geometry}
\RequirePackage[pdfusetitle, colorlinks]{hyperref}
\RequirePackage[shortlabels, inline]{enumitem}
\RequirePackage[titles]{tocloft}
\RequirePackage{tabularx, fancyhdr, tabularray, titlesec, apptools, abstract, xcolor, xpatch, calc, etoolbox, abstract}
\usepackage{setspace}
\usepackage{etoolbox}
\usepackage{array} 

\newcolumntype{Y}{>{\centering\arraybackslash}X}

% Gráficos
\RequirePackage{graphicx, pdfpages, pdflscape, pgfplots, tcolorbox, graphbox}
\RequirePackage[outline]{contour}
\RequirePackage[hang, labelfont=bf, labelsep=period, margin=0.3cm, skip=3pt, format=plain]{caption}
\RequirePackage{subcaption}

%[figurename=Fig.]{caption} Cambiar Figura.

% Bibliografía
\RequirePackage[backend=biber,bibstyle=ieee,citestyle=numeric-comp,sorting=none]{biblatex}
\RequirePackage[style=mexican]{csquotes}
\usepackage{authblk}
\renewcommand\Authand{, }
\renewcommand\Authands{, }
\renewcommand{\Affilfont}{\scriptsize}

% --- Configuraciones adicionales de paquetes ---

% Versión de PGFplots
\pgfplotsset{compat=newest}

% Librerías de pgfplots
\usepgfplotslibrary{colormaps}
\usepackage{pgfplotstable}

% Librerías de tikz
\usetikzlibrary{babel, calc, scopes, intersections, angles, quotes, arrows, arrows.meta, backgrounds, shapes.geometric, patterns, shadows, perspective, external}

% Definición de estilos de Tikz, etc.
\tikzset{%
	% Configuraciones de tikz particulares del documento, como estilos de nodos y dibujos
	font = {\selectfont},
	frame/.style={thin, dashed, lightgray, line cap=round, rounded corners=5pt}
}

% Grosor de contorno adicional (para emplearse en gráficos)
\contourlength{1pt}

% Directorios de gráficos
\graphicspath{{imágenes/}{escudos/}}

% Todos los enlaces del documento en negro
\hypersetup{allcolors=black}

% Librerías de tabularray
\UseTblrLibrary{booktabs}
\UseTblrLibrary{amsmath}

% --- Configuraciones adicionales de diseño ---

% Colores
\definecolor{principaluno}{HTML}{000000}% Negro
\definecolor{principaldos}{HTML}{EAEDEF}% Gris claro
\definecolor{secuno}{HTML}{0897D5}% Azul claro
\definecolor{secdos}{HTML}{E8442A}% Naranja
\definecolor{sectres}{HTML}{7F9297}% Gris oscuro
\definecolor{seccuatro}{HTML}{F6F7F7}% Casi blanco

% Diseño de títulos de sección
\titleformat{\section}
{\normalfont\normalsize\bfseries}{\thesection.}{1ex}{}

\titleformat{\subsection}
{\normalfont\small\bfseries}{\thesubsection.}{1ex}{}

\titleformat{\subsubsection}
{\small\bfseries}{\thetitle.}{\widthof{\enspace}}{}

\AtAppendix{%
    \titleformat{\section}[block]
    {\normalfont\normalsize\bfseries}{\appendixname\ \thesection.}{1ex}{\color{principaluno}}
}

% Tokens para llenar el documento
\newtoks\subtitle
\newtoks\subject
\newtoks\email

% Personalización del título de tablas largas con tabularray
\NewTblrTheme{replab}{
	\SetTblrStyle{caption-tag}{font=\bfseries}
	\DefTblrTemplate{caption-sep}{default}{\bfseries.\enskip}
}

% --- Página de título de documento ---
\makeatletter
	\renewcommand\maketitle{%

    	\renewcommand\thefootnote{\@fnsymbol\c@footnote}%
    	\def\@makefnmark{\rlap{\@textsuperscript{\normalfont\@thefnmark}}}%
    	\long\def\@makefntext##1{\parindent 1em\noindent
    			\hb@xt@1.8em{%
    			  \hss\@textsuperscript{\normalfont\@thefnmark}}##1}%
    
        \begin{center}%
			\begin{tblr}{
			colspec = {Q[c, wd=.125\textwidth] Q[c, wd=.6\textwidth] Q[c, wd=.125\textwidth]},
			rows = {m} 
			}
				\includegraphics[width=.125\textwidth]{unam} &
				
				\begin{tabular}{c}
					\bfseries\large\the\subject \\ [0.25cm]
					\bfseries\large\@title \\ [0.25cm]
					\bfseries\Large\the\subtitle \\ [0.25cm]
				\end{tabular} &
			
				\includegraphics[width=.125\textwidth]{fcunam}
			\end{tblr}
    		
    		\medskip
    
    		\@author
    		
    		\medskip
    		
			\small
    		\@date
    
        \end{center}
    
        \thispagestyle{plain}
    
    	\medskip
	}
\makeatother

% Rediseño del estilo plain
\fancypagestyle{plain}{%
	\renewcommand{\headrulewidth}{0pt}
	
	\fancyhf{}
	\fancyfoot[c]{%
		\begin{tblr}{c c c}
			
			&  &
			
		\end{tblr}
	}
}



% Diseño de los encabezados y pies de página
\fancypagestyle{fancy}{%
    \xpretocmd\headrule{\color{principaluno}}{}{\PatchFailed}% Cambio de color de la regla en el encabezado
    
    \fancyhf{}
    \fancyhead[le]{%
    	\begin{tblr}{
			colspec = {Q[c,m] Q[l,m]},
			colsep = 2pt
		}
    		\includegraphics[
				align=c,
				width=3ex]{fcunam}% Escudo de la instittución
    		& {\small{Facultad de Ciencias UNAM}}
    	\end{tblr}
    }

    \fancyhead[re]{%
    	\thepage
    }

    \fancyhead[lo]{%
    	\begin{tblr}{
			colspec = {Q[c,m] Q[l,m]},
			colsep = 2pt
		}
    		\includegraphics[
				align=c,
				width=3ex]{fcunam}% Escudo de la instittución
    		& {\small\textit{\the\subject}}
    	\end{tblr}
    }
    
    \fancyhead[ro]{%
        \thepage
    }
    
    \fancyfoot[c]{%
    	\begin{tblr}{c c c}
    		
    		&  &
    		
    	\end{tblr}
    }
}
